package com.shana.ssm.mapper;

import com.shana.ssm.pojo.Category;
import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    int deleteByPrimaryKey(Integer cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    Category selectByPrimaryKey(Integer cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    int updateByPrimaryKey(Category record);
}