package com.shana.ssm.mapper;

import com.shana.ssm.pojo.Good;
import com.shana.ssm.vo.QueryVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    int deleteByPrimaryKey(Integer goodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    Good selectByPrimaryKey(Integer goodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    List<Good> selectAll();

    List<Good> selectLimitedGoods(@Param("qv") QueryVo qv);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    int updateByPrimaryKey(Good record);

    void deleteSome(@Param("strs") String[] strs);
}