package com.shana.ssm.pojo;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.cateid
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private Integer cateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.catename
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private String catename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.cateid
     *
     * @return the value of t_category.cateid
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public Integer getCateid() {
        return cateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.cateid
     *
     * @param cateid the value for t_category.cateid
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setCateid(Integer cateid) {
        this.cateid = cateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.catename
     *
     * @return the value of t_category.catename
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public String getCatename() {
        return catename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.catename
     *
     * @param catename the value for t_category.catename
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setCatename(String catename) {
        this.catename = catename == null ? null : catename.trim();
    }
}