package com.shana.ssm.pojo;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

@Data
public class Good {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goodid
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private Integer goodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gname
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.count
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.price
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.nowprice
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private Double nowprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.address
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goodimg
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private String goodimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.createDate
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.state
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goodid
     *
     * @return the value of t_goods.goodid
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goodid
     *
     * @param goodid the value for t_goods.goodid
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.gname
     *
     * @return the value of t_goods.gname
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.gname
     *
     * @param gname the value for t_goods.gname
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.count
     *
     * @return the value of t_goods.count
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.count
     *
     * @param count the value for t_goods.count
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.price
     *
     * @return the value of t_goods.price
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.price
     *
     * @param price the value for t_goods.price
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.nowprice
     *
     * @return the value of t_goods.nowprice
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public Double getNowprice() {
        return nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.nowprice
     *
     * @param nowprice the value for t_goods.nowprice
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setNowprice(Double nowprice) {
        this.nowprice = nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.address
     *
     * @return the value of t_goods.address
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.address
     *
     * @param address the value for t_goods.address
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goodimg
     *
     * @return the value of t_goods.goodimg
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public String getGoodimg() {
        return goodimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goodimg
     *
     * @param goodimg the value for t_goods.goodimg
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setGoodimg(String goodimg) {
        this.goodimg = goodimg == null ? null : goodimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.category
     *
     * @return the value of t_goods.category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.category
     *
     * @param category the value for t_goods.category
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.createDate
     *
     * @return the value of t_goods.createDate
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.createDate
     *
     * @param createdate the value for t_goods.createDate
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.state
     *
     * @return the value of t_goods.state
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.state
     *
     * @param state the value for t_goods.state
     *
     * @mbg.generated Thu Sep 26 19:02:13 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}